#!/bin/bash

__BASE_PATH=$PWD
__BACKUP_ROOT=$HOME/.envDeploy_backup

source ${__BASE_PATH}/env_config/git_config

backup_config() {
	if [ ! -d $__BACKUP_ROOT ] ; then
		mkdir -p $__BACKUP_ROOT
	fi

	cp -v ~/.bashrc $__BACKUP_ROOT/bashrc.user
	cp -v ~/.profile $__BACKUP_ROOT/profile.user
	cp -v ~/.vimrc $__BACKUP_ROOT/vimrc.user
	cp -v /etc/bash.bashrc $__BACKUP_ROOT/bashrc.etc
}

clean_config() {
	rm ~/.vimrc
	rm ~/.tmux.conf
	rm -rf ~/.vim
	rm -rf ~/.gitconfig

	if [ -d $__BACKUP_ROOT ] ; then
		cp -v $__BACKUP_ROOT/bashrc.user ~/.basrc
		cp -v $__BACKUP_ROOT/profile.user ~/.profile
		cp -v $__BACKUP_ROOT/vimrc.user ~/.vimrc
		cp -v $__BACKUP_ROOT/bashrc.etc /etc/bash.bashrc
	fi
}

apply_config() {
	local src=$1
	local dst=$2

	if [ ! -f $dst ]
	then
		cat $src >> $dst
	else
		diff $dst $src | grep '^>' | cut -c 3- >> $dst
	fi
}

update_and_install_packages() {
	apt-get update
	apt-get upgrade -y

	echo "Installing Developer Tools ... "
	apt-get install silversearcher-ag cifs-utils tig exuberant-ctags cscope vim tmux screen shellcheck build-essential curl git jq landscape-common inxi ssh htop libncurses-dev nmon parallel debootstrap pv -y

	echo "Install Build Dependencies ... "
	apt-get install libelf-dev flex bison libssl-dev git openssh-server telnetd nfs-kernel-server samba php-cli php-pgsql manpages-dev python3 zstd -y

	echo "Install Btrfs Development Dependencies ... "
	apt-get install autogen autoconf pkg-config xmlto asciidoc e2fslibs-dev libblkid-dev zlib1g-dev libzstd-dev liblzo2-dev btrfs-progs -y

	echo "Install BCC Dependencies ... "
	apt-get install python3-pip libclang-dev llvm arping netperf iperf cmake -y

	echo "Install Virtual Development Board Dependencies ... "
	apt-get install qemu libncurses5-dev gcc-arm-linux-gnueabi build-essential gcc-arm-none-eabi gcc-aarch64-linux-gnu -y

	echo "Repair Ubuntu chinese characters issue ... "
	apt-get remove fonts-arphic-ukai fonts-arphic-uming -y

	echo "Remove Automatic Updates on Ubuntu ..."
	apt-get remove unattended-upgrades
}

setup_bash_env() {
	echo "Set up Bash Env. ..."
	apply_config ./bash_config/bashrc.etc /etc/bash.bashrc
	apply_config ./bash_config/bashrc.user ~/.bashrc
	apply_config ./bash_config/profile ~/.profile
	echo "source ${PWD}/bash_config/bash_command_timer.sh" >> ~/.bashrc
}

install_tools() {
#	echo "Install Google Chrome ..."
#	wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#	sudo dpkg -i ./google-chrome*.deb
#	sudo apt-get install -f -y
#	rm -f ./google-chrome*.deb

	echo "Install /bin tools ... "
#	cp ./tools/tl /bin
#	cp ./tools/diskage /bin
#	echo '/bin/tl &' >> ~/.bashrc
#	echo 'killall tl > /dev/null 2>&1' >> ~/.bash_logout
}

setup_VIM_env() {
	echo "Install VIM plugins ..."
	git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
	ln -s ${__BASE_PATH}/vim_config/v2.current/vimrc ~/.vimrc
	vim +PluginInstall +qall
}

setup_sys_env() {
	echo "System ENV Setup"

	#soft-link to tmux.conf
	ln -s ${__BASE_PATH}/env_config/tmux.conf ~/.tmux.conf

#	echo "Set up /tmp RamDisk ..."

#	cp tools/ramtmp.sh /etc/init.d/
#	chmod 755 /etc/init.d/ramtmp.sh
#	ln -s /etc/init.d/ramtmp.sh /etc/rcS.d/S50ramtmp.sh
}

main() {
	if [ "$(`which id` -u)" -ne 0 ]; then
		echo "Sorry, must be root"
		exit 1
	fi

	update_and_install_packages
	if [ $? -ne 0 ] ; then
		echo "error occurs in update_and_install_packages()"
		exit 1
	fi

	setup_bash_env
	if [ $? -ne 0 ] ; then
		echo "error occurs in setup_bash_env()"
		exit 1
	fi

	install_tools
	if [ $? -ne 0 ] ; then
		echo "error occurs in install_tools()"
		exit 1
	fi

	setup_VIM_env
	if [ $? -ne 0 ] ; then
		echo "error occurs in setup_VIM_env()"
		exit 1
	fi

	setup_GIT_env
	if [ $? -ne 0 ] ; then
		echo "error occurs in setup_GIT_env()"
		exit 1
	fi

	setup_sys_env
	if [ $? -ne 0 ] ; then
		echo "error occurs in setup_sys_env()"
		exit 1
	fi

	echo "DONE"
	exit 0
}

#main
#exit 0

# Allows to call a function based on arguments passed to the script
$*
