#!/bin/sh

__GIT_USER_NAME="Ming-Feng Wei"
__GIT_USER_EMAIL="xxx@xxx.xxx"

setup_GIT_env() {
	echo "Set up GIT configurations ..."

	git config --global user.name "${__GIT_USER_NAME}"
	git config --global user.email "${__GIT_USER_EMAIL}"
	git config --global core.filemode true
	git config --global core.editor vim
	git config --global alias.st status
	git config --global alias.ci commit
	git config --global alias.co checkout
	git config --global alias.br branch
	git config --global alias.df diff
	git config --global alias.pick cherry-pick
	git config --global alias.fp format-patch
	git config --global alias.la "log --graph --decorate --pretty=oneline --abbrev-commit --all"
	git config --global alias.ll "log --graph --decorate --pretty=oneline --abbrev-commit"
	git config --global alias.lf "log --stat --decorate --format=fuller abbrev-commit"
	git config --global color.ui auto
	git config --global color.diff auto
	git config --global color.status auto
	git config --global color.branch auto
	git config --global color.log auto
	git config --global push.default simple
}
